name: Build and Publish Binaries

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Build and Publish Binaries
        run: |
          make release
          mkdir -p release
          cp -r bin/release/* release/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.ref }}-$(date +%s)
          release_name: Release ${{ github.ref }}-$(date +%s)
          draft: false
          prerelease: false

      - name: upload asset leetoclock-helper-linux-arm64
        id: asset-leetoclock-helper-linux-arm64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/
          asset_name: leetoclock-helper-linux-arm64
          asset_content_type: application/octet-stream

      - name: upload asset leetoclock-helper-linux-386
        id: asset-leetoclock-helper-linux-386
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/
          asset_name: leetoclock-helper-linux-386
          asset_content_type: application/octet-stream

      - name: upload asset leetoclock-helper-linux-arm
        id: asset-leetoclock-helper-linux-arm
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/
          asset_name: leetoclock-helper-linux-arm
          asset_content_type: application/octet-stream

      - name: upload asset leetoclock-helper-linux-amd64
        id: asset-leetoclock-helper-linux-amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/
          asset_name: leetoclock-helper-linux-amd64
          asset_content_type: application/octet-stream

      - name: upload asset leetoclock-helper-darwin-amd64
        id: asset-leetoclock-helper-darwin-amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/
          asset_name: leetoclock-helper-darwin-amd64
          asset_content_type: application/octet-stream

      - name: upload asset leetoclock-helper-windows-amd64
        id: asset-leetoclock-helper-windows-amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/
          asset_name: leetoclock-helper-windows-amd64.exe
          asset_content_type: application/octet-stream

      - name: upload asset leetoclock-helper-windows-386
        id: asset-leetoclock-helper-windows-386
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/
          asset_name: leetoclock-helper-windows-386.exe
          asset_content_type: application/octet-stream

      - name: upload asset leetoclock-helper-windows-arm
        id: asset-leetoclock-helper-windows-arm
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/
          asset_name: leetoclock-helper-windows-arm.exe
          asset_content_type: application/octet-stream
